// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartComposed01Preview from "@/registry/vibe-ui/chart-composed-01/chart-composed-01.tsx";

export const Route = createFileRoute("/preview/charts/composed/chart-composed-01")({
  head: () => ({
    meta: [{ title: "chart-composed-01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-composed-01 Preview" },
  component: () => <PreviewPage Preview={ChartComposed01Preview} section="charts" />,
});
