// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartComposed02Preview from "@/registry/vibe-ui/chart-composed-02/chart-composed-02.tsx";

export const Route = createFileRoute("/preview/charts/composed/chart-composed-02")({
  head: () => ({
    meta: [{ title: "chart-composed-02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-composed-02 Preview" },
  component: () => <PreviewPage Preview={ChartComposed02Preview} section="charts" />,
});
