// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Button02Preview from "@/registry/vibe-ui/button-02/button-02.tsx";

export const Route = createFileRoute("/preview/components/button/button-02")({
  head: () => ({
    meta: [{ title: "Button 02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Button 02 Preview" },
  component: () => <PreviewPage Preview={Button02Preview} type="registry:component" />,
});
