// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryPreviewPage } from "@/features/registry/components/registry-preview-page";
import Button03Preview from "@/registry/vibe-ui/button-03/button-03.tsx";

export const Route = createFileRoute("/preview/components/button/button-03")({
  head: () => ({
    meta: [{ title: "Button 03 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Button 03 Preview" },
  component: () => <RegistryPreviewPage Preview={Button03Preview} type="registry:component" />,
});
