// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Button04Preview from "@/registry/vibe-ui/button-04/button-04.tsx";

export const Route = createFileRoute("/preview/components/button/button-04")({
  head: () => ({
    meta: [{ title: "Search Button Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Search Button Preview" },
  component: () => <PreviewPage Preview={Button04Preview} section="components" />,
});
