// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Button01Preview from "@/registry/vibe-ui/button-01/button-01.tsx";

export const Route = createFileRoute("/preview/components/button/button-01")({
  head: () => ({
    meta: [{ title: "Button 01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Button 01 Preview" },
  component: () => <PreviewPage Preview={Button01Preview} type="registry:component" />,
});
