import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it } from "vite-plus/test";

import {
  buildRegistryRoutes,
  generatedRouteFiles,
} from "../../../../scripts/build-registry-routes.ts";
import type { VibeRegistryItem } from "../types/registry.ts";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { force: true, recursive: true })));
});

async function fixture() {
  const root = await mkdtemp(path.join(tmpdir(), "vibeui-route-gen-"));
  roots.push(root);

  return {
    root,
    routesRoot: path.join(root, "src/routes"),
  };
}

describe("Registry route generation", () => {
  it("generates Section and Collection routes with direct canonical imports and metadata", async () => {
    const paths = await fixture();
    const files = generatedRouteFiles(defaultItems(), paths.routesRoot, paths.root);
    const index = files.get(path.join(paths.routesRoot, "_rootLayout/components/index.tsx"));
    const button = files.get(path.join(paths.routesRoot, "_rootLayout/components/button.tsx"));

    expect(index).toContain('createFileRoute("/_rootLayout/components/")');
    expect(index).toContain("itemCount: 2,");
    expect(button).toContain(
      'import Button01Preview1 from "../../../../registry/vibe-ui/button-01/button-01.tsx";',
    );
    expect(button).toContain(
      'import Button02Preview2 from "../../../../registry/vibe-ui/button-02/button-02.tsx";',
    );
    expect(button).toContain('name: "button-01",');
    expect(button).toContain('title: "Button 02",');
    expect(button).toContain("satisfies RegistryCollectionItem[]");
  });

  it("generates separate Collection routes when types share a category", async () => {
    const paths = await fixture();
    const files = generatedRouteFiles(
      [
        registryItem({ name: "button-01", type: "registry:component" }),
        registryItem({ name: "button-hero-01", type: "registry:block" }),
      ],
      paths.routesRoot,
      paths.root,
    );

    expect(files.get(path.join(paths.routesRoot, "_rootLayout/components/button.tsx"))).toContain(
      'createFileRoute("/_rootLayout/components/button")',
    );
    expect(files.get(path.join(paths.routesRoot, "_rootLayout/blocks/button.tsx"))).toContain(
      'createFileRoute("/_rootLayout/blocks/button")',
    );
  });

  it("removes stale generated route files", async () => {
    const paths = await fixture();

    await buildRegistryRoutes(paths);
    await writeFile(
      path.join(paths.routesRoot, "_rootLayout/components/card.tsx"),
      "// @generated by scripts/build-registry-routes.ts\nstale\n",
      "utf8",
    );

    await buildRegistryRoutes(paths);

    await expect(
      readFile(path.join(paths.routesRoot, "_rootLayout/components/card.tsx"), "utf8"),
    ).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("refuses to overwrite handwritten route files", async () => {
    const paths = await fixture();
    const routeFile = path.join(paths.routesRoot, "_rootLayout/components/button.tsx");
    await mkdir(path.dirname(routeFile), { recursive: true });
    await writeFile(routeFile, "export const handwritten = true;\n", "utf8");

    await expect(buildRegistryRoutes(paths)).rejects.toThrow(/Refusing to overwrite/);
  });

  it("detects stale generated output in check mode", async () => {
    const paths = await fixture();

    await buildRegistryRoutes(paths);
    await writeFile(
      path.join(paths.routesRoot, "_rootLayout/components/button.tsx"),
      "// @generated by scripts/build-registry-routes.ts\nstale\n",
      "utf8",
    );

    await expect(buildRegistryRoutes({ ...paths, check: true })).rejects.toThrow(
      /Generated Registry routes are stale/,
    );
  });
});

function defaultItems() {
  return [
    registryItem({ name: "button-01" }),
    registryItem({ description: "A loud button.", name: "button-02", title: "Button 02" }),
    registryItem({
      category: "hero-section",
      name: "hero-section-01",
      title: "Hero Section 01",
      type: "registry:block",
    }),
    registryItem({
      category: "landing-pages",
      name: "landing-page-01",
      title: "Landing Page 01",
      type: "registry:page",
    }),
  ];
}

function registryItem({
  category = "button",
  description = "A quiet button.",
  name,
  title = "Button 01",
  type = "registry:component",
}: {
  category?: string;
  description?: string;
  name: string;
  title?: string;
  type?: "registry:block" | "registry:component" | "registry:page";
}): VibeRegistryItem {
  return {
    categories: [category],
    description,
    files: [
      {
        path: `registry/vibe-ui/${name}/${name}.tsx`,
        target: `@components/vibe-ui/${name}/${name}.tsx`,
        type,
      },
    ],
    name,
    registryDependencies: [],
    title,
    type,
  } as VibeRegistryItem;
}
