import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it } from "vite-plus/test";

import {
  buildRegistrySidebar,
  sidebarContent,
} from "../../../../scripts/build-registry-sidebar.ts";
import type { VibeRegistryItem } from "../types/registry.ts";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { force: true, recursive: true })));
});

async function fixture() {
  const root = await mkdtemp(path.join(tmpdir(), "vibeui-sidebar-gen-"));
  roots.push(root);

  const outputFile = path.join(root, "src/features/registry/data/registry-sidebar.gen.ts");

  return { outputFile };
}

describe("Registry sidebar generation", () => {
  it("generates ordered sidebar data with kind labels, Collection titles, and hrefs", async () => {
    const sidebar = sidebarContent([
      registryItem({ category: "card", name: "card-01", title: "Card" }),
      registryItem({ category: "button", name: "button-01", title: "Button" }),
      registryItem({
        category: "hero-section",
        name: "hero-section-01",
        title: "Hero",
        type: "registry:block",
      }),
    ]);
    expect(sidebar).toContain("// @generated by scripts/build-registry-sidebar.ts");
    expect(sidebar).toContain('"label": "Components"');
    expect(sidebar).toContain('"type": "registry:component"');
    expect(sidebar.indexOf('"title": "Button"')).toBeLessThan(sidebar.indexOf('"title": "Card"'));
    expect(sidebar).toContain('"href": "/components/button"');
    expect(sidebar).toContain('"href": "/blocks/hero-section"');
  });

  it("detects stale generated output in check mode", async () => {
    const paths = await fixture();

    await buildRegistrySidebar(paths);
    await writeFile(
      paths.outputFile,
      "// @generated by scripts/build-registry-sidebar.ts\nstale\n",
    );

    await expect(buildRegistrySidebar({ ...paths, check: true })).rejects.toThrow(
      /Generated Registry sidebar is stale/,
    );
  });

  it("refuses to overwrite a handwritten sidebar file", async () => {
    const paths = await fixture();
    await mkdir(path.dirname(paths.outputFile), { recursive: true });
    await writeFile(paths.outputFile, "export const handwritten = true;\n", "utf8");

    await expect(buildRegistrySidebar(paths)).rejects.toThrow(/Refusing to overwrite/);
  });
});

function registryItem({
  category,
  name,
  title,
  type = "registry:component",
}: {
  category: string;
  name: string;
  title: string;
  type?: "registry:block" | "registry:component" | "registry:page";
}): VibeRegistryItem {
  return {
    categories: [category],
    description: `${title} description.`,
    files: [
      {
        path: `registry/vibe-ui/${name}/${name}.tsx`,
        target: `@components/vibe-ui/${name}/${name}.tsx`,
        type,
      },
    ],
    name,
    registryDependencies: [],
    title,
    type,
  } as VibeRegistryItem;
}
