// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartRadial02Preview from "@/registry/vibe-ui/chart-radial-02/chart-radial-02.tsx";

export const Route = createFileRoute("/preview/charts/radial/chart-radial-02")({
  head: () => ({
    meta: [{ title: "chart-radial-02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-radial-02 Preview" },
  component: () => <PreviewPage Preview={ChartRadial02Preview} section="charts" />,
});
