// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartRadial01Preview from "@/registry/vibe-ui/chart-radial-01/chart-radial-01.tsx";

export const Route = createFileRoute("/preview/charts/radial/chart-radial-01")({
  head: () => ({
    meta: [{ title: "chart-radial-01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-radial-01 Preview" },
  component: () => <PreviewPage Preview={ChartRadial01Preview} section="charts" />,
});
