// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartRadar02Preview from "@/registry/vibe-ui/chart-radar-02/chart-radar-02.tsx";

export const Route = createFileRoute("/preview/charts/radar/chart-radar-02")({
  head: () => ({
    meta: [{ title: "chart-radar-02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-radar-02 Preview" },
  component: () => <PreviewPage Preview={ChartRadar02Preview} section="charts" />,
});
