// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartRadar01Preview from "@/registry/vibe-ui/chart-radar-01/chart-radar-01.tsx";

export const Route = createFileRoute("/preview/charts/radar/chart-radar-01")({
  head: () => ({
    meta: [{ title: "chart-radar-01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-radar-01 Preview" },
  component: () => <PreviewPage Preview={ChartRadar01Preview} section="charts" />,
});
