// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartLine03Preview from "@/registry/vibe-ui/chart-line-03/chart-line-03.tsx";

export const Route = createFileRoute("/preview/charts/line/chart-line-03")({
  head: () => ({
    meta: [{ title: "chart-line-03 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-line-03 Preview" },
  component: () => <PreviewPage Preview={ChartLine03Preview} section="charts" />,
});
