// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartLine04Preview from "@/registry/vibe-ui/chart-line-04/chart-line-04.tsx";

export const Route = createFileRoute("/preview/charts/line/chart-line-04")({
  head: () => ({
    meta: [{ title: "Subscriber growth · TanStack Charts Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Subscriber growth · TanStack Charts Preview" },
  component: () => <PreviewPage Preview={ChartLine04Preview} section="charts" />,
});
