// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartLine02Preview from "@/registry/vibe-ui/chart-line-02/chart-line-02.tsx";

export const Route = createFileRoute("/preview/charts/line/chart-line-02")({
  head: () => ({
    meta: [{ title: "chart-line-02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-line-02 Preview" },
  component: () => <PreviewPage Preview={ChartLine02Preview} section="charts" />,
});
