// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartLine01Preview from "@/registry/vibe-ui/chart-line-01/chart-line-01.tsx";

export const Route = createFileRoute("/preview/charts/line/chart-line-01")({
  head: () => ({
    meta: [{ title: "chart-line-01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-line-01 Preview" },
  component: () => <PreviewPage Preview={ChartLine01Preview} section="charts" />,
});
