// @generated by scripts/build-registry-routes.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistrySectionPage } from "@/features/registry/components/registry-section-page";

const collections = [
  {
    href: "/pages/landing-pages",
    itemCount: 1,
    title: "Landing Pages",
  },
];

export const Route = createFileRoute("/_rootLayout/pages/")({
  staticData: { ariaLabel: "Pages" },
  component: () => (
    <RegistrySectionPage
      collections={collections}
      description={"Browse complete page compositions grouped by purpose."}
      title={"Pages"}
    />
  ),
});
