// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemLandingPage01 from "@/features/registry/data/items/landing-page-01.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [registryItemLandingPage01] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/pages/landing-pages")({
  staticData: { ariaLabel: "Landing Pages" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse landing pages Registry items."}
      items={items}
      title={"Landing Pages"}
    />
  ),
});
