// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import {
  RegistryCollectionPage,
  type RegistryCollectionItem,
} from "@/features/registry/components/registry-collection-page";

const items = [
  {
    description: "A complete landing page with navigation, hero, and social proof.",
    name: "landing-page-01",
    previewHref: "/preview/pages/landing-pages/landing-page-01",
    title: "Landing Page 01",
  },
] satisfies RegistryCollectionItem[];

export const Route = createFileRoute("/_rootLayout/pages/landing-pages")({
  staticData: { ariaLabel: "Landing Pages" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse landing pages Registry items."}
      items={items}
      title={"Landing Pages"}
    />
  ),
});
