// @generated by scripts/build-registry-routes.ts
import { createFileRoute } from "@tanstack/react-router";

import {
  RegistryCollectionPage,
  type RegistryCollectionItem,
} from "@/features/registry/components/registry-collection-page";

import LandingPage01Preview1 from "../../../../registry/vibe-ui/landing-page-01/landing-page-01.tsx";

const items = [
  {
    Preview: LandingPage01Preview1,
    description: "A complete landing page with navigation, hero, and social proof.",
    name: "landing-page-01",
    title: "Landing Page 01",
  },
] satisfies RegistryCollectionItem[];

export const Route = createFileRoute("/_rootLayout/pages/landing-pages")({
  staticData: { ariaLabel: "Landing Pages" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse landing pages Registry items."}
      eyebrow={"Pages"}
      items={items}
      title={"Landing Pages"}
    />
  ),
});
