// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartPie01Preview from "@/registry/vibe-ui/chart-pie-01/chart-pie-01.tsx";

export const Route = createFileRoute("/preview/charts/pie/chart-pie-01")({
  head: () => ({
    meta: [{ title: "chart-pie-01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-pie-01 Preview" },
  component: () => <PreviewPage Preview={ChartPie01Preview} section="charts" />,
});
