// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartPie02Preview from "@/registry/vibe-ui/chart-pie-02/chart-pie-02.tsx";

export const Route = createFileRoute("/preview/charts/pie/chart-pie-02")({
  head: () => ({
    meta: [{ title: "chart-pie-02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-pie-02 Preview" },
  component: () => <PreviewPage Preview={ChartPie02Preview} section="charts" />,
});
