// @generated by scripts/build-registry.ts
import type { VibeRegistrySectionSummary } from "../types/registry";

export const registrySections = [
  {
    collections: [
      {
        href: "/components/button",
        title: "Button",
      },
      {
        href: "/components/form",
        title: "Form",
      },
      {
        href: "/components/table",
        title: "Table",
      },
    ],
    label: "Components",
    href: "/components",
    section: "components",
  },
  {
    collections: [
      {
        href: "/blocks/hero-section",
        title: "Hero Section",
      },
    ],
    label: "Blocks",
    href: "/blocks",
    section: "blocks",
  },
  {
    collections: [
      {
        href: "/charts/area",
        title: "Area",
      },
      {
        href: "/charts/bar",
        title: "Bar",
      },
      {
        href: "/charts/composed",
        title: "Composed",
      },
      {
        href: "/charts/line",
        title: "Line",
      },
      {
        href: "/charts/map",
        title: "Map",
      },
      {
        href: "/charts/pie",
        title: "Pie",
      },
      {
        href: "/charts/radar",
        title: "Radar",
      },
      {
        href: "/charts/radial",
        title: "Radial",
      },
    ],
    label: "Charts",
    href: "/charts",
    section: "charts",
  },
  {
    collections: [
      {
        href: "/pages/landing-pages",
        title: "Landing Pages",
      },
    ],
    label: "Pages",
    href: "/pages",
    section: "pages",
  },
] satisfies VibeRegistrySectionSummary[];
