// @generated by scripts/build-registry-sidebar.ts
import type { VibeRegistrySidebarSection } from "../types/registry";

export const registrySidebarSections = [
  {
    "collections": [
      {
        "href": "/components/button",
        "title": "Button"
      }
    ],
    "label": "Components",
    "type": "registry:component"
  },
  {
    "collections": [
      {
        "href": "/blocks/hero-section",
        "title": "Hero Section"
      }
    ],
    "label": "Blocks",
    "type": "registry:block"
  },
  {
    "collections": [
      {
        "href": "/pages/landing-pages",
        "title": "Landing Pages"
      }
    ],
    "label": "Pages",
    "type": "registry:page"
  }
] satisfies VibeRegistrySidebarSection[];
