// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartBar02Preview from "@/registry/vibe-ui/chart-bar-02/chart-bar-02.tsx";

export const Route = createFileRoute("/preview/charts/bar/chart-bar-02")({
  head: () => ({
    meta: [{ title: "chart-bar-02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-bar-02 Preview" },
  component: () => <PreviewPage Preview={ChartBar02Preview} section="charts" />,
});
