// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartBar03Preview from "@/registry/vibe-ui/chart-bar-03/chart-bar-03.tsx";

export const Route = createFileRoute("/preview/charts/bar/chart-bar-03")({
  head: () => ({
    meta: [{ title: "Acquisition channels · TanStack Charts Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Acquisition channels · TanStack Charts Preview" },
  component: () => <PreviewPage Preview={ChartBar03Preview} section="charts" />,
});
