// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartBar01Preview from "@/registry/vibe-ui/chart-bar-01/chart-bar-01.tsx";

export const Route = createFileRoute("/preview/charts/bar/chart-bar-01")({
  head: () => ({
    meta: [{ title: "chart-bar-01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-bar-01 Preview" },
  component: () => <PreviewPage Preview={ChartBar01Preview} section="charts" />,
});
