// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import LandingPage01Preview from "@/registry/vibe-ui/landing-page-01/landing-page-01.tsx";

export const Route = createFileRoute("/preview/pages/landing-pages/landing-page-01")({
  head: () => ({
    meta: [{ title: "Landing Page 01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Landing Page 01 Preview" },
  component: () => <PreviewPage Preview={LandingPage01Preview} section="pages" />,
});
