import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import sourceRegistry from "../registry.json" with { type: "json" };
import type {
  VibeRegistry,
  VibeRegistryItemType,
  VibeRegistryItem,
} from "../src/features/registry/types/registry.ts";

const generatedHeader = "// @generated by scripts/build-registry-routes.ts\n";
const projectRoot = path.resolve(import.meta.dirname, "..");
const registry = sourceRegistry as VibeRegistry;

const segmentByType: Record<VibeRegistryItemType, string> = {
  "registry:block": "blocks",
  "registry:component": "components",
  "registry:page": "pages",
};

const labelByType: Record<VibeRegistryItemType, string> = {
  "registry:block": "Blocks",
  "registry:component": "Components",
  "registry:page": "Pages",
};

const descriptionByType: Record<VibeRegistryItemType, string> = {
  "registry:block": "Browse complete interface sections and application patterns.",
  "registry:component": "Browse focused UI components grouped by category.",
  "registry:page": "Browse complete page compositions grouped by purpose.",
};

type Collection = {
  category: string;
  href: string;
  items: VibeRegistryItem[];
  title: string;
  type: VibeRegistryItemType;
};

export type BuildRegistryRoutesOptions = {
  check?: boolean;
  routesRoot?: string;
};

export async function buildRegistryRoutes({
  check = false,
  routesRoot = path.join(projectRoot, "src/routes"),
}: BuildRegistryRoutesOptions): Promise<void> {
  const { items } = registry;
  const expected = generatedRouteFiles(items, routesRoot, projectRoot);
  const generatedDirectories = new Set([...expected.keys()].map((file) => path.dirname(file)));
  const staleFiles = await staleGeneratedFiles(generatedDirectories, expected);
  const staleMessages = [...staleFiles].map((file) => `stale generated route: ${file}`);
  const mismatches: string[] = [];

  for (const [file, content] of expected) {
    const existing = await readOptional(file);

    if (existing !== undefined && !existing.startsWith(generatedHeader)) {
      throw new Error(`Refusing to overwrite handwritten route file: ${file}`);
    }

    if (existing !== content) mismatches.push(file);
  }

  if (check) {
    if (mismatches.length > 0 || staleMessages.length > 0) {
      throw new Error(
        [
          "Generated Registry routes are stale.",
          ...mismatches.map((file) => `update needed: ${file}`),
          ...staleMessages,
        ].join("\n"),
      );
    }

    return;
  }

  for (const [file, content] of expected) {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content, "utf8");
  }

  for (const file of staleFiles) {
    await unlink(file);
  }
}

export function generatedRouteFiles(
  items: readonly VibeRegistryItem[],
  routesRoot: string,
  registryRoot: string,
): Map<string, string> {
  const collections = registryCollections(items);
  const files = new Map<string, string>();

  for (const type of ["registry:component", "registry:block", "registry:page"] as const) {
    const sectionCollections = collections.filter((collection) => collection.type === type);
    if (sectionCollections.length === 0) continue;

    const directory = path.join(routesRoot, "_rootLayout", segmentByType[type]);
    files.set(
      path.join(directory, "index.tsx"),
      sectionRouteContent({ collections: sectionCollections, type }),
    );

    for (const collection of sectionCollections) {
      const routeFile = path.join(directory, `${collection.category}.tsx`);
      files.set(routeFile, collectionRouteContent({ collection, registryRoot, routeFile }));
    }
  }

  return files;
}

function registryCollections(items: readonly VibeRegistryItem[]): Collection[] {
  const grouped = new Map<string, Collection>();

  for (const item of items) {
    const category = item.categories[0]!;
    const key = `${item.type}:${category}`;
    const existing = grouped.get(key);

    if (existing === undefined) {
      grouped.set(key, {
        category,
        href: `/${segmentByType[item.type]}/${category}`,
        items: [item],
        title: humanize(category),
        type: item.type,
      });
    } else {
      existing.items.push(item);
    }
  }

  return [...grouped.values()].sort((left, right) =>
    `${left.type}:${left.category}`.localeCompare(`${right.type}:${right.category}`),
  );
}

function sectionRouteContent({
  collections,
  type,
}: {
  collections: Collection[];
  type: VibeRegistryItemType;
}): string {
  return `${generatedHeader}import { createFileRoute } from "@tanstack/react-router";

import { RegistrySectionPage } from "@/features/registry/components/registry-section-page";

const collections = ${objectArray(
    collections.map(({ href, items, title }) => ({
      href,
      itemCount: items.length,
      title,
    })),
  )};

export const Route = createFileRoute("/_rootLayout/${segmentByType[type]}/")({
  staticData: { ariaLabel: ${stringLiteral(labelByType[type])} },
  component: () => (
    <RegistrySectionPage
      collections={collections}
      description=${jsxStringLiteral(descriptionByType[type])}
      title=${jsxStringLiteral(labelByType[type])}
    />
  ),
});
`;
}

function collectionRouteContent({
  collection,
  registryRoot,
  routeFile,
}: {
  collection: Collection;
  registryRoot: string;
  routeFile: string;
}): string {
  const imports = collection.items
    .map((item, index) => {
      const importName = `${pascalCase(item.name)}Preview${index + 1}`;
      const importPath = moduleSpecifier(
        routeFile,
        path.join(registryRoot, "registry/vibe-ui", item.name, `${item.name}.tsx`),
      );
      return { importName, line: `import ${importName} from "${importPath}";` };
    })
    .map(({ line }) => line)
    .join("\n");
  const serializedItems = objectArray(
    collection.items.map((item, index) => ({
      Preview: raw(`${pascalCase(item.name)}Preview${index + 1}`),
      description: item.description,
      name: item.name,
      title: item.title,
    })),
  );

  return `${generatedHeader}import { createFileRoute } from "@tanstack/react-router";

import {
  RegistryCollectionPage,
  type RegistryCollectionItem,
} from "@/features/registry/components/registry-collection-page";

${imports}

const items = ${serializedItems} satisfies RegistryCollectionItem[];

export const Route = createFileRoute("/_rootLayout/${segmentByType[collection.type]}/${collection.category}")({
  staticData: { ariaLabel: ${stringLiteral(collection.title)} },
  component: () => (
    <RegistryCollectionPage
      description=${jsxStringLiteral(`Browse ${collection.title.toLowerCase()} Registry items.`)}
      eyebrow=${jsxStringLiteral(labelByType[collection.type])}
      items={items}
      title=${jsxStringLiteral(collection.title)}
    />
  ),
});
`;
}

async function staleGeneratedFiles(
  directories: Set<string>,
  expected: Map<string, string>,
): Promise<Set<string>> {
  const stale = new Set<string>();

  for (const directory of directories) {
    const entries = await readdir(directory, { withFileTypes: true }).catch(() => []);
    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith(".tsx")) continue;

      const file = path.join(directory, entry.name);
      if (expected.has(file)) continue;

      const content = await readOptional(file);
      if (content?.startsWith(generatedHeader)) stale.add(file);
    }
  }

  return stale;
}

async function readOptional(file: string): Promise<string | undefined> {
  return await readFile(file, "utf8").catch((error: unknown) => {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return undefined;
    throw error;
  });
}

function moduleSpecifier(fromFile: string, toFile: string): string {
  const relative = path.relative(path.dirname(fromFile), toFile).replaceAll(path.sep, "/");
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function pascalCase(value: string): string {
  return value
    .split("-")
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

function humanize(value: string): string {
  return value
    .split("-")
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join(" ");
}

type RawExpression = {
  raw: string;
};

function raw(value: string): RawExpression {
  return { raw: value };
}

function objectArray(values: readonly Record<string, RawExpression | number | string>[]): string {
  if (values.length === 0) return "[]";

  return `[
${values.map((value) => objectLiteral(value, 2)).join(",\n")},
]`;
}

function objectLiteral(
  value: Record<string, RawExpression | number | string>,
  indent: number,
): string {
  const spaces = " ".repeat(indent);
  const childSpaces = " ".repeat(indent + 2);

  return `${spaces}{
${Object.entries(value)
  .map(([key, entry]) => `${childSpaces}${key}: ${literal(entry)},`)
  .join("\n")}
${spaces}}`;
}

function literal(value: RawExpression | number | string): string {
  if (typeof value === "object") return value.raw;
  if (typeof value === "number") return String(value);
  return stringLiteral(value);
}

function stringLiteral(value: string): string {
  return JSON.stringify(value);
}

function jsxStringLiteral(value: string): string {
  return `{${stringLiteral(value)}}`;
}

if (import.meta.filename === process.argv[1]) {
  await buildRegistryRoutes({ check: process.argv.includes("--check") });
  process.stdout.write(
    process.argv.includes("--check")
      ? "Generated Registry routes are up to date.\n"
      : "Generated Registry routes.\n",
  );
}
