import { execFileSync } from "node:child_process";
import { cp, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { isDeepStrictEqual } from "node:util";

import sourceRegistry from "../registry.json" with { type: "json" };
import {
  registryItemSummaries,
  registryPreviewHref,
  registrySections,
  segmentByType,
} from "../src/features/registry/lib/registry-catalog.ts";
import {
  type VibeBuiltRegistryItem,
  type VibeRegistry,
  type VibeRegistryCollection,
  type VibeRegistryItem,
  type VibeRegistryItemSummary,
  type VibeRegistrySection,
  vibeBuiltRegistryItemSchema,
  vibeRegistryItemSchema,
  vibeRegistrySchema,
} from "../src/features/registry/types/registry.ts";

const generatedHeader = "// @generated by scripts/build-registry.ts\n";
const projectRoot = path.resolve(import.meta.dirname, "..");
const registryRouteSegments = ["components", "blocks", "pages"] as const;

async function buildRegistry(): Promise<void> {
  vibeRegistrySchema.parse(sourceRegistry);
  const temporaryRootPath = await mkdtemp(path.join(tmpdir(), "vibeui-registry-"));
  const temporaryItemsPath = path.join(temporaryRootPath, "items");
  const itemsPath = path.join(projectRoot, "src/features/registry/data/items");
  const publicRegistryPath = path.join(projectRoot, "public/r");

  try {
    execFileSync("shadcn", ["build", "--output", temporaryItemsPath], { stdio: "inherit" });
    const registry = await readBuiltRegistryOutput(temporaryItemsPath);

    await replaceBuiltRegistryData(temporaryItemsPath, itemsPath, publicRegistryPath);
    await writeRegistryOutputs(
      registry,
      path.join(projectRoot, "src/routes/_rootLayout"),
      path.join(projectRoot, "src/features/registry/data/registry-sidebar.gen.ts"),
    );
  } finally {
    await rm(temporaryRootPath, { force: true, recursive: true });
  }
}

export async function readBuiltRegistryOutput(itemsPath: string): Promise<VibeRegistry> {
  const aggregate = vibeRegistrySchema.parse(
    JSON.parse(await readFile(path.join(itemsPath, "registry.json"), "utf8")),
  );
  const entries = await readdir(itemsPath, { withFileTypes: true });
  const itemFileNames = entries
    .filter(
      (entry) => entry.isFile() && entry.name.endsWith(".json") && entry.name !== "registry.json",
    )
    .map((entry) => entry.name)
    .sort();
  const expectedFileNames = aggregate.items.map((item) => `${item.name}.json`).sort();
  const missingFileNames = expectedFileNames.filter(
    (fileName) => !itemFileNames.includes(fileName),
  );
  const extraFileNames = itemFileNames.filter((fileName) => !expectedFileNames.includes(fileName));

  if (missingFileNames.length > 0 || extraFileNames.length > 0) {
    throw new Error(
      `Built Registry item files do not match the aggregate. Missing: ${missingFileNames.join(", ") || "none"}. Extra: ${extraFileNames.join(", ") || "none"}.`,
    );
  }

  const aggregateItems = new Map(aggregate.items.map((item) => [item.name, item]));

  for (const fileName of itemFileNames) {
    const builtItem = vibeBuiltRegistryItemSchema.parse(
      JSON.parse(await readFile(path.join(itemsPath, fileName), "utf8")),
    );
    const fileItemName = fileName.slice(0, -".json".length);

    if (builtItem.name !== fileItemName) {
      throw new Error(
        `Built Registry item ${fileName} declares the unexpected name ${builtItem.name}.`,
      );
    }

    const aggregateItem = aggregateItems.get(builtItem.name)!;
    if (!isDeepStrictEqual(registryItemWithoutContent(builtItem), aggregateItem)) {
      throw new Error(`Built Registry item ${fileName} does not match the aggregate metadata.`);
    }
  }

  return aggregate;
}

export async function replaceBuiltRegistryData(
  sourcePath: string,
  itemsPath: string,
  publicRegistryPath: string,
): Promise<void> {
  await rm(itemsPath, { force: true, recursive: true });
  await mkdir(path.dirname(itemsPath), { recursive: true });
  await cp(sourcePath, itemsPath, { recursive: true });

  await rm(publicRegistryPath, { force: true, recursive: true });
  await mkdir(path.dirname(publicRegistryPath), { recursive: true });
  await cp(itemsPath, publicRegistryPath, { recursive: true });
}

function registryItemWithoutContent(item: VibeBuiltRegistryItem): VibeRegistryItem {
  const itemMetadata: Record<string, unknown> = { ...item };
  delete itemMetadata.$schema;

  return vibeRegistryItemSchema.parse({
    ...itemMetadata,
    files: item.files.map((file) => {
      const metadata: Record<string, unknown> = { ...file };
      delete metadata.content;
      return metadata;
    }),
  });
}

export async function writeRegistryOutputs(
  registry: VibeRegistry,
  routesRootPath: string,
  sidebarFile: string,
): Promise<void> {
  const [routeFiles, sidebarContent] = renderRegistryOutputs(registry, routesRootPath);
  const previewRoutesRootPath = path.join(path.dirname(routesRootPath), "preview");

  await Promise.all([
    ...registryRouteSegments.map((segment) =>
      rm(path.join(routesRootPath, segment), { force: true, recursive: true }),
    ),
    ...registryRouteSegments.map((segment) =>
      rm(path.join(previewRoutesRootPath, segment), { force: true, recursive: true }),
    ),
    rm(sidebarFile, { force: true }),
  ]);

  for (const [file, content] of routeFiles) {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content, "utf8");
  }

  await mkdir(path.dirname(sidebarFile), { recursive: true });
  await writeFile(sidebarFile, sidebarContent, "utf8");
}

export function renderRegistryOutputs(registry: VibeRegistry, routesRootPath: string) {
  const sections = registrySections(registryItemSummaries(registry.items));

  const routeFiles = new Map<string, string>();

  for (const section of sections) {
    const sectionRouteDir = path.join(routesRootPath, segmentByType[section.type]);
    routeFiles.set(path.join(sectionRouteDir, "index.tsx"), sectionRouteContent(section));

    for (const collection of section.collections) {
      const routeFile = path.join(sectionRouteDir, `${collection.category}.tsx`);
      routeFiles.set(routeFile, collectionRouteContent(collection));

      for (const item of collection.items) {
        const previewRouteFile = path.join(
          path.dirname(routesRootPath),
          "preview",
          segmentByType[item.type],
          item.category,
          `${item.name}.tsx`,
        );
        routeFiles.set(previewRouteFile, previewRouteContent(item));
      }
    }
  }

  return [routeFiles, sidebarContent(sections)] as const;
}

function sectionRouteContent(section: VibeRegistrySection): string {
  const collections = JSON.stringify(
    section.collections.map(({ href, items, title }) => ({
      title,
      href,
      itemCount: items.length,
    })),
  );

  return `${generatedHeader}import { createFileRoute } from "@tanstack/react-router";

import { RegistrySectionPage } from "@/features/registry/components/registry-section-page";

const collections = ${collections};

export const Route = createFileRoute("/_rootLayout${section.href}/")({
  staticData: { ariaLabel: ${JSON.stringify(section.title)} },
  component: () => (
    <RegistrySectionPage
      collections={collections}
      description={${JSON.stringify(section.description)}}
      title={${JSON.stringify(section.title)}}
    />
  ),
});
`;
}

function collectionRouteContent(collection: VibeRegistryCollection): string {
  const itemImports = collection.items
    .map(
      (item) =>
        `import ${registryItemImportName(item.name)} from "@/features/registry/data/items/${item.name}.json";`,
    )
    .join("\n");
  const items = collection.items.map((item) => registryItemImportName(item.name)).join(", ");

  return `${generatedHeader}import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
${itemImports}
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [${items}] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout${collection.href}")({
  staticData: { ariaLabel: ${JSON.stringify(collection.title)} },
  component: () => (
    <RegistryCollectionPage
      description={${JSON.stringify(collection.description)}}
      items={items}
      title={${JSON.stringify(collection.title)}}
    />
  ),
});
`;
}

function previewRouteContent(item: VibeRegistryItemSummary): string {
  const importName = `${pascalCase(item.name)}Preview`;
  const href = registryPreviewHref(item.type, item.category, item.name);
  const importPath = `@/registry/vibe-ui/${item.name}/${item.name}.tsx`;

  return `${generatedHeader}import { createFileRoute } from "@tanstack/react-router";

import { RegistryPreviewPage } from "@/features/registry/components/registry-preview-page";
import ${importName} from "${importPath}";

export const Route = createFileRoute(${JSON.stringify(href)})({
  head: () => ({
    meta: [{ title: ${JSON.stringify(`${item.title} Preview – VibeUI`)} }],
  }),
  staticData: { ariaLabel: ${JSON.stringify(`${item.title} Preview`)} },
  component: () => (
    <RegistryPreviewPage Preview={${importName}} type=${JSON.stringify(item.type)} />
  ),
});
`;
}

function sidebarContent(sections: readonly VibeRegistrySection[]): string {
  const sidebarSections = sections.map(({ collections, title, type }) => ({
    collections: collections.map(({ href, title: collectionTitle }) => ({
      href,
      title: collectionTitle,
    })),
    label: title,
    type,
  }));

  return `${generatedHeader}import type { VibeRegistrySidebarSection } from "../types/registry";

export const registrySidebarSections = ${JSON.stringify(sidebarSections, null, 2)} satisfies VibeRegistrySidebarSection[];
`;
}

function pascalCase(value: string): string {
  return value
    .split("-")
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

function registryItemImportName(value: string): string {
  return `registryItem${pascalCase(value)}`;
}

if (import.meta.filename === process.argv[1]) {
  await buildRegistry();
}
