import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import sourceRegistry from "../registry.json" with { type: "json" };
import type {
  VibeRegistry,
  VibeRegistryItemType,
  VibeRegistryItem,
} from "../src/features/registry/types/registry.ts";

const generatedHeader = "// @generated by scripts/build-registry-sidebar.ts\n";
const projectRoot = path.resolve(import.meta.dirname, "..");
const registry = sourceRegistry as VibeRegistry;

const segmentByType: Record<VibeRegistryItemType, string> = {
  "registry:block": "blocks",
  "registry:component": "components",
  "registry:page": "pages",
};

const labelByType: Record<VibeRegistryItemType, string> = {
  "registry:block": "Blocks",
  "registry:component": "Components",
  "registry:page": "Pages",
};

type Collection = {
  href: string;
  title: string;
  type: VibeRegistryItemType;
};

export type BuildRegistrySidebarOptions = {
  check?: boolean;
  outputFile?: string;
};

export async function buildRegistrySidebar({
  check = false,
  outputFile = path.join(projectRoot, "src/features/registry/data/registry-sidebar.gen.ts"),
}: BuildRegistrySidebarOptions = {}): Promise<void> {
  const { items } = registry;
  const content = sidebarContent(items);
  const existing = await readFile(outputFile, "utf8").catch((error: unknown) => {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return undefined;
    throw error;
  });

  if (existing !== undefined && !existing.startsWith(generatedHeader)) {
    throw new Error(`Refusing to overwrite handwritten sidebar file: ${outputFile}`);
  }

  if (check) {
    if (existing !== content) {
      throw new Error(`Generated Registry sidebar is stale: ${outputFile}`);
    }

    return;
  }

  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, content, "utf8");
}

export function sidebarContent(items: readonly VibeRegistryItem[]): string {
  const collections = registryCollections(items);
  const sections = (["registry:component", "registry:block", "registry:page"] as const).flatMap(
    (type) => {
      const matchingCollections = collections.filter((collection) => collection.type === type);
      if (matchingCollections.length === 0) return [];

      return {
        collections: matchingCollections.map(({ href, title }) => ({ href, title })),
        label: labelByType[type],
        type,
      };
    },
  );

  return `${generatedHeader}import type { VibeRegistrySidebarSection } from "../types/registry";

export const registrySidebarSections = ${JSON.stringify(sections, null, 2)} satisfies VibeRegistrySidebarSection[];
`;
}

function registryCollections(items: readonly VibeRegistryItem[]): Collection[] {
  const grouped = new Map<string, Collection>();

  for (const item of items) {
    const category = item.categories[0]!;
    const key = `${item.type}:${category}`;

    if (!grouped.has(key)) {
      grouped.set(key, {
        href: `/${segmentByType[item.type]}/${category}`,
        title: humanize(category),
        type: item.type,
      });
    }
  }

  return [...grouped.values()].sort((left, right) =>
    `${left.type}:${left.title}`.localeCompare(`${right.type}:${right.title}`),
  );
}

function humanize(value: string): string {
  return value
    .split("-")
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join(" ");
}

if (import.meta.filename === process.argv[1]) {
  await buildRegistrySidebar({ check: process.argv.includes("--check") });
  process.stdout.write(
    process.argv.includes("--check")
      ? "Generated Registry sidebar is up to date.\n"
      : "Generated Registry sidebar.\n",
  );
}
