import { execFileSync } from "node:child_process";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import sourceRegistry from "../registry.json" with { type: "json" };
import {
  registryItemSummaries,
  registrySections,
  segmentByType,
} from "../src/features/registry/lib/registry-catalog.ts";
import {
  type VibeRegistry,
  type VibeRegistryCollection,
  type VibeRegistrySection,
  vibeRegistrySchema,
} from "../src/features/registry/types/registry.ts";

const generatedHeader = "// @generated by scripts/build-registry.ts\n";
const projectRoot = path.resolve(import.meta.dirname, "..");
const registryRouteSegments = ["components", "blocks", "pages"] as const;

async function buildRegistry(): Promise<void> {
  const registry = vibeRegistrySchema.parse(sourceRegistry);
  await rm(path.join(projectRoot, "public/r"), { force: true, recursive: true });
  execFileSync("shadcn", ["build"], { stdio: "inherit" });
  await writeRegistryOutputs(
    registry,
    path.join(projectRoot, "src/routes/_rootLayout"),
    path.join(projectRoot, "src/features/registry/data/registry-sidebar.gen.ts"),
  );
}

export async function writeRegistryOutputs(
  registry: VibeRegistry,
  routesRootPath: string,
  sidebarFile: string,
): Promise<void> {
  const [routeFiles, sidebarContent] = renderRegistryOutputs(registry, routesRootPath);

  await Promise.all([
    ...registryRouteSegments.map((segment) =>
      rm(path.join(routesRootPath, segment), { force: true, recursive: true }),
    ),
    rm(sidebarFile, { force: true }),
  ]);

  for (const [file, content] of routeFiles) {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content, "utf8");
  }

  await mkdir(path.dirname(sidebarFile), { recursive: true });
  await writeFile(sidebarFile, sidebarContent, "utf8");
}

export function renderRegistryOutputs(registry: VibeRegistry, routesRootPath: string) {
  const sections = registrySections(registryItemSummaries(registry.items));

  const routeFiles = new Map<string, string>();

  for (const section of sections) {
    const sectionRouteDir = path.join(routesRootPath, segmentByType[section.type]);
    routeFiles.set(path.join(sectionRouteDir, "index.tsx"), sectionRouteContent(section));

    for (const collection of section.collections) {
      const routeFile = path.join(sectionRouteDir, `${collection.category}.tsx`);
      routeFiles.set(routeFile, collectionRouteContent(collection));
    }
  }

  return [routeFiles, sidebarContent(sections)] as const;
}

function sectionRouteContent(section: VibeRegistrySection): string {
  const collections = JSON.stringify(
    section.collections.map(({ href, items, title }) => ({
      title,
      href,
      itemCount: items.length,
    })),
  );

  return `${generatedHeader}import { createFileRoute } from "@tanstack/react-router";

import { RegistrySectionPage } from "@/features/registry/components/registry-section-page";

const collections = ${collections};

export const Route = createFileRoute("/_rootLayout${section.href}/")({
  staticData: { ariaLabel: ${JSON.stringify(section.title)} },
  component: () => (
    <RegistrySectionPage
      collections={collections}
      description={${JSON.stringify(section.description)}}
      title={${JSON.stringify(section.title)}}
    />
  ),
});
`;
}

function collectionRouteContent(collection: VibeRegistryCollection): string {
  const imports = collection.items
    .map((item, index) => {
      const importName = `${pascalCase(item.name)}Preview${index + 1}`;
      const importPath = `@/registry/vibe-ui/${item.name}/${item.name}.tsx`;
      return `import ${importName} from "${importPath}";`;
    })
    .join("\n");

  const items = collection.items
    .map(
      (item, index) =>
        `{Preview:${pascalCase(item.name)}Preview${index + 1},description:${JSON.stringify(item.description)},name:${JSON.stringify(item.name)},title:${JSON.stringify(item.title)}}`,
    )
    .join(",");

  return `${generatedHeader}import { createFileRoute } from "@tanstack/react-router";

import {
  RegistryCollectionPage,
  type RegistryCollectionItem,
} from "@/features/registry/components/registry-collection-page";

${imports}

const items = [${items}] satisfies RegistryCollectionItem[];

export const Route = createFileRoute("/_rootLayout${collection.href}")({
  staticData: { ariaLabel: ${JSON.stringify(collection.title)} },
  component: () => (
    <RegistryCollectionPage
      description={${JSON.stringify(collection.description)}}
      items={items}
      title={${JSON.stringify(collection.title)}}
    />
  ),
});
`;
}

function sidebarContent(sections: readonly VibeRegistrySection[]): string {
  const sidebarSections = sections.map(({ collections, title, type }) => ({
    collections: collections.map(({ href, title: collectionTitle }) => ({
      href,
      title: collectionTitle,
    })),
    label: title,
    type,
  }));

  return `${generatedHeader}import type { VibeRegistrySidebarSection } from "../types/registry";

export const registrySidebarSections = ${JSON.stringify(sidebarSections, null, 2)} satisfies VibeRegistrySidebarSection[];
`;
}

function pascalCase(value: string): string {
  return value
    .split("-")
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

if (import.meta.filename === process.argv[1]) {
  await buildRegistry();
}
