// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import {
  RegistryCollectionPage,
  type RegistryCollectionItem,
} from "@/features/registry/components/registry-collection-page";

const items = [
  {
    description: "A primary action button with a compact leading icon.",
    name: "button-01",
    previewHref: "/preview/components/button/button-01",
    title: "Button 01",
  },
  {
    description: "A quiet secondary action with a trailing keyboard hint.",
    name: "button-02",
    previewHref: "/preview/components/button/button-02",
    title: "Button 02",
  },
  {
    description: "A composed action button built from multiple source files.",
    name: "button-03",
    previewHref: "/preview/components/button/button-03",
    title: "Button 03",
  },
] satisfies RegistryCollectionItem[];

export const Route = createFileRoute("/_rootLayout/components/button")({
  staticData: { ariaLabel: "Button" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse button Registry items."}
      items={items}
      title={"Button"}
    />
  ),
});
