// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemButton01 from "@/features/registry/data/items/button-01.json";
import registryItemButton02 from "@/features/registry/data/items/button-02.json";
import registryItemButton03 from "@/features/registry/data/items/button-03.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [
  registryItemButton01,
  registryItemButton02,
  registryItemButton03,
] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/components/button")({
  staticData: { ariaLabel: "Button" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse button Registry items."}
      items={items}
      title={"Button"}
    />
  ),
});
