// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemForm01 from "@/features/registry/data/items/form-01.json";
import registryItemForm02 from "@/features/registry/data/items/form-02.json";
import registryItemForm03 from "@/features/registry/data/items/form-03.json";
import registryItemForm04 from "@/features/registry/data/items/form-04.json";
import registryItemForm05 from "@/features/registry/data/items/form-05.json";
import registryItemForm06 from "@/features/registry/data/items/form-06.json";
import registryItemForm07 from "@/features/registry/data/items/form-07.json";
import registryItemForm08 from "@/features/registry/data/items/form-08.json";
import registryItemForm09 from "@/features/registry/data/items/form-09.json";
import registryItemForm10 from "@/features/registry/data/items/form-10.json";
import registryItemForm11 from "@/features/registry/data/items/form-11.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [
  registryItemForm01,
  registryItemForm02,
  registryItemForm03,
  registryItemForm04,
  registryItemForm05,
  registryItemForm06,
  registryItemForm07,
  registryItemForm08,
  registryItemForm09,
  registryItemForm10,
  registryItemForm11,
] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/components/form")({
  staticData: { ariaLabel: "Form" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse form Registry items."}
      items={items}
      title={"Form"}
    />
  ),
});
