// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistrySectionPage } from "@/features/registry/components/registry-section-page";

const collections = [{ title: "Button", href: "/components/button", itemCount: 3 }];

export const Route = createFileRoute("/_rootLayout/components/")({
  staticData: { ariaLabel: "Components" },
  component: () => (
    <RegistrySectionPage
      collections={collections}
      description={"Browse focused UI components grouped by category."}
      title={"Components"}
    />
  ),
});
