// @generated by scripts/build-registry-routes.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistrySectionPage } from "@/features/registry/components/registry-section-page";

const collections = [
  {
    href: "/components/button",
    itemCount: 2,
    title: "Button",
  },
];

export const Route = createFileRoute("/_rootLayout/components/")({
  staticData: { ariaLabel: "Components" },
  component: () => (
    <RegistrySectionPage
      collections={collections}
      description={"Browse focused UI components grouped by category."}
      title={"Components"}
    />
  ),
});
