// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemTable01 from "@/features/registry/data/items/table-01.json";
import registryItemTable02 from "@/features/registry/data/items/table-02.json";
import registryItemTable03 from "@/features/registry/data/items/table-03.json";
import registryItemTable04 from "@/features/registry/data/items/table-04.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [
  registryItemTable01,
  registryItemTable02,
  registryItemTable03,
  registryItemTable04,
] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/components/table")({
  staticData: { ariaLabel: "Table" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse table Registry items."}
      items={items}
      title={"Table"}
    />
  ),
});
