// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartArea02Preview from "@/registry/vibe-ui/chart-area-02/chart-area-02.tsx";

export const Route = createFileRoute("/preview/charts/area/chart-area-02")({
  head: () => ({
    meta: [{ title: "chart-area-02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-area-02 Preview" },
  component: () => <PreviewPage Preview={ChartArea02Preview} section="charts" />,
});
