// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartArea01Preview from "@/registry/vibe-ui/chart-area-01/chart-area-01.tsx";

export const Route = createFileRoute("/preview/charts/area/chart-area-01")({
  head: () => ({
    meta: [{ title: "chart-area-01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "chart-area-01 Preview" },
  component: () => <PreviewPage Preview={ChartArea01Preview} section="charts" />,
});
