// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartArea03Preview from "@/registry/vibe-ui/chart-area-03/chart-area-03.tsx";

export const Route = createFileRoute("/preview/charts/area/chart-area-03")({
  head: () => ({
    meta: [{ title: "Monthly revenue · TanStack Charts Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Monthly revenue · TanStack Charts Preview" },
  component: () => <PreviewPage Preview={ChartArea03Preview} section="charts" />,
});
