// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemChartComposed01 from "@/features/registry/data/items/chart-composed-01.json";
import registryItemChartComposed02 from "@/features/registry/data/items/chart-composed-02.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [registryItemChartComposed01, registryItemChartComposed02] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/charts/composed")({
  staticData: { ariaLabel: "Composed" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse composed Registry items."}
      items={items}
      title={"Composed"}
    />
  ),
});
