// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistrySectionPage } from "@/features/registry/components/registry-section-page";

const collections = [
  { title: "Area", href: "/charts/area", itemCount: 3 },
  { title: "Bar", href: "/charts/bar", itemCount: 3 },
  { title: "Composed", href: "/charts/composed", itemCount: 2 },
  { title: "Line", href: "/charts/line", itemCount: 4 },
  { title: "Map", href: "/charts/map", itemCount: 2 },
  { title: "Pie", href: "/charts/pie", itemCount: 2 },
  { title: "Radar", href: "/charts/radar", itemCount: 2 },
  { title: "Radial", href: "/charts/radial", itemCount: 2 },
];

export const Route = createFileRoute("/_rootLayout/charts/")({
  staticData: { ariaLabel: "Charts" },
  component: () => (
    <RegistrySectionPage
      collections={collections}
      description={"Explore chart cards for trends, comparisons, and distributions."}
      title={"Charts"}
    />
  ),
});
