// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemChartLine01 from "@/features/registry/data/items/chart-line-01.json";
import registryItemChartLine02 from "@/features/registry/data/items/chart-line-02.json";
import registryItemChartLine03 from "@/features/registry/data/items/chart-line-03.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [
  registryItemChartLine01,
  registryItemChartLine02,
  registryItemChartLine03,
] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/charts/line")({
  staticData: { ariaLabel: "Line" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse line Registry items."}
      items={items}
      title={"Line"}
    />
  ),
});
