// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemChartPie01 from "@/features/registry/data/items/chart-pie-01.json";
import registryItemChartPie02 from "@/features/registry/data/items/chart-pie-02.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [registryItemChartPie01, registryItemChartPie02] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/charts/pie")({
  staticData: { ariaLabel: "Pie" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse pie Registry items."}
      items={items}
      title={"Pie"}
    />
  ),
});
