// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemChartRadar01 from "@/features/registry/data/items/chart-radar-01.json";
import registryItemChartRadar02 from "@/features/registry/data/items/chart-radar-02.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [registryItemChartRadar01, registryItemChartRadar02] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/charts/radar")({
  staticData: { ariaLabel: "Radar" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse radar Registry items."}
      items={items}
      title={"Radar"}
    />
  ),
});
