// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemChartRadial01 from "@/features/registry/data/items/chart-radial-01.json";
import registryItemChartRadial02 from "@/features/registry/data/items/chart-radial-02.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [registryItemChartRadial01, registryItemChartRadial02] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/charts/radial")({
  staticData: { ariaLabel: "Radial" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse radial Registry items."}
      items={items}
      title={"Radial"}
    />
  ),
});
