// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Table02Preview from "@/registry/vibe-ui/table-02/table-02.tsx";

export const Route = createFileRoute("/preview/components/table/table-02")({
  head: () => ({
    meta: [{ title: "Table 02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Table 02 Preview" },
  component: () => <PreviewPage Preview={Table02Preview} section="components" />,
});
