// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Table01Preview from "@/registry/vibe-ui/table-01/table-01.tsx";

export const Route = createFileRoute("/preview/components/table/table-01")({
  head: () => ({
    meta: [{ title: "Table 01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Table 01 Preview" },
  component: () => <PreviewPage Preview={Table01Preview} type="registry:component" />,
});
