// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Table03Preview from "@/registry/vibe-ui/table-03/table-03.tsx";

export const Route = createFileRoute("/preview/components/table/table-03")({
  head: () => ({
    meta: [{ title: "Table 03 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Table 03 Preview" },
  component: () => <PreviewPage Preview={Table03Preview} type="registry:component" />,
});
