// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Table04Preview from "@/registry/vibe-ui/table-04/table-04.tsx";

export const Route = createFileRoute("/preview/components/table/table-04")({
  head: () => ({
    meta: [{ title: "Table 04 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Table 04 Preview" },
  component: () => <PreviewPage Preview={Table04Preview} section="components" />,
});
