/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootLayoutRouteRouteImport } from './routes/_rootLayout/route'
import { Route as PreviewRouteRouteImport } from './routes/preview/route'
import { Route as RootLayoutIndexRouteImport } from './routes/_rootLayout/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as RootLayoutBlocksIndexRouteImport } from './routes/_rootLayout/blocks/index'
import { Route as RootLayoutBlocksHeroSectionRouteImport } from './routes/_rootLayout/blocks/hero-section'
import { Route as RootLayoutComponentsIndexRouteImport } from './routes/_rootLayout/components/index'
import { Route as RootLayoutComponentsButtonRouteImport } from './routes/_rootLayout/components/button'
import { Route as RootLayoutComponentsFormRouteImport } from './routes/_rootLayout/components/form'
import { Route as RootLayoutPagesIndexRouteImport } from './routes/_rootLayout/pages/index'
import { Route as RootLayoutPagesLandingPagesRouteImport } from './routes/_rootLayout/pages/landing-pages'
import { Route as PreviewBlocksHeroSectionHeroSection01RouteImport } from './routes/preview/blocks/hero-section/hero-section-01'
import { Route as PreviewComponentsButtonButton01RouteImport } from './routes/preview/components/button/button-01'
import { Route as PreviewComponentsButtonButton02RouteImport } from './routes/preview/components/button/button-02'
import { Route as PreviewComponentsButtonButton03RouteImport } from './routes/preview/components/button/button-03'
import { Route as PreviewComponentsFormForm01RouteImport } from './routes/preview/components/form/form-01'
import { Route as PreviewComponentsFormForm02RouteImport } from './routes/preview/components/form/form-02'
import { Route as PreviewComponentsFormForm03RouteImport } from './routes/preview/components/form/form-03'
import { Route as PreviewComponentsFormForm04RouteImport } from './routes/preview/components/form/form-04'
import { Route as PreviewComponentsFormForm05RouteImport } from './routes/preview/components/form/form-05'
import { Route as PreviewComponentsFormForm06RouteImport } from './routes/preview/components/form/form-06'
import { Route as PreviewComponentsFormForm07RouteImport } from './routes/preview/components/form/form-07'
import { Route as PreviewComponentsFormForm08RouteImport } from './routes/preview/components/form/form-08'
import { Route as PreviewComponentsFormForm09RouteImport } from './routes/preview/components/form/form-09'
import { Route as PreviewComponentsFormForm10RouteImport } from './routes/preview/components/form/form-10'
import { Route as PreviewComponentsFormForm11RouteImport } from './routes/preview/components/form/form-11'
import { Route as PreviewPagesLandingPagesLandingPage01RouteImport } from './routes/preview/pages/landing-pages/landing-page-01'

const RootLayoutRouteRoute = RootLayoutRouteRouteImport.update({
  id: '/_rootLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRouteRoute = PreviewRouteRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutIndexRoute = RootLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutBlocksIndexRoute = RootLayoutBlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)
const RootLayoutBlocksHeroSectionRoute =
  RootLayoutBlocksHeroSectionRouteImport.update({
    id: '/blocks/hero-section',
    path: '/blocks/hero-section',
    getParentRoute: () => RootLayoutRouteRoute,
  } as any)
const RootLayoutComponentsIndexRoute =
  RootLayoutComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => RootLayoutRouteRoute,
  } as any)
const RootLayoutComponentsButtonRoute =
  RootLayoutComponentsButtonRouteImport.update({
    id: '/components/button',
    path: '/components/button',
    getParentRoute: () => RootLayoutRouteRoute,
  } as any)
const RootLayoutComponentsFormRoute =
  RootLayoutComponentsFormRouteImport.update({
    id: '/components/form',
    path: '/components/form',
    getParentRoute: () => RootLayoutRouteRoute,
  } as any)
const RootLayoutPagesIndexRoute = RootLayoutPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)
const RootLayoutPagesLandingPagesRoute =
  RootLayoutPagesLandingPagesRouteImport.update({
    id: '/pages/landing-pages',
    path: '/pages/landing-pages',
    getParentRoute: () => RootLayoutRouteRoute,
  } as any)
const PreviewBlocksHeroSectionHeroSection01Route =
  PreviewBlocksHeroSectionHeroSection01RouteImport.update({
    id: '/blocks/hero-section/hero-section-01',
    path: '/blocks/hero-section/hero-section-01',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsButtonButton01Route =
  PreviewComponentsButtonButton01RouteImport.update({
    id: '/components/button/button-01',
    path: '/components/button/button-01',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsButtonButton02Route =
  PreviewComponentsButtonButton02RouteImport.update({
    id: '/components/button/button-02',
    path: '/components/button/button-02',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsButtonButton03Route =
  PreviewComponentsButtonButton03RouteImport.update({
    id: '/components/button/button-03',
    path: '/components/button/button-03',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm01Route =
  PreviewComponentsFormForm01RouteImport.update({
    id: '/components/form/form-01',
    path: '/components/form/form-01',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm02Route =
  PreviewComponentsFormForm02RouteImport.update({
    id: '/components/form/form-02',
    path: '/components/form/form-02',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm03Route =
  PreviewComponentsFormForm03RouteImport.update({
    id: '/components/form/form-03',
    path: '/components/form/form-03',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm04Route =
  PreviewComponentsFormForm04RouteImport.update({
    id: '/components/form/form-04',
    path: '/components/form/form-04',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm05Route =
  PreviewComponentsFormForm05RouteImport.update({
    id: '/components/form/form-05',
    path: '/components/form/form-05',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm06Route =
  PreviewComponentsFormForm06RouteImport.update({
    id: '/components/form/form-06',
    path: '/components/form/form-06',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm07Route =
  PreviewComponentsFormForm07RouteImport.update({
    id: '/components/form/form-07',
    path: '/components/form/form-07',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm08Route =
  PreviewComponentsFormForm08RouteImport.update({
    id: '/components/form/form-08',
    path: '/components/form/form-08',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm09Route =
  PreviewComponentsFormForm09RouteImport.update({
    id: '/components/form/form-09',
    path: '/components/form/form-09',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm10Route =
  PreviewComponentsFormForm10RouteImport.update({
    id: '/components/form/form-10',
    path: '/components/form/form-10',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewComponentsFormForm11Route =
  PreviewComponentsFormForm11RouteImport.update({
    id: '/components/form/form-11',
    path: '/components/form/form-11',
    getParentRoute: () => PreviewRouteRoute,
  } as any)
const PreviewPagesLandingPagesLandingPage01Route =
  PreviewPagesLandingPagesLandingPage01RouteImport.update({
    id: '/pages/landing-pages/landing-page-01',
    path: '/pages/landing-pages/landing-page-01',
    getParentRoute: () => PreviewRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof RootLayoutIndexRoute
  '/preview': typeof PreviewRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/blocks/hero-section': typeof RootLayoutBlocksHeroSectionRoute
  '/components/button': typeof RootLayoutComponentsButtonRoute
  '/components/form': typeof RootLayoutComponentsFormRoute
  '/pages/landing-pages': typeof RootLayoutPagesLandingPagesRoute
  '/blocks/': typeof RootLayoutBlocksIndexRoute
  '/components/': typeof RootLayoutComponentsIndexRoute
  '/pages/': typeof RootLayoutPagesIndexRoute
  '/preview/blocks/hero-section/hero-section-01': typeof PreviewBlocksHeroSectionHeroSection01Route
  '/preview/components/button/button-01': typeof PreviewComponentsButtonButton01Route
  '/preview/components/button/button-02': typeof PreviewComponentsButtonButton02Route
  '/preview/components/button/button-03': typeof PreviewComponentsButtonButton03Route
  '/preview/components/form/form-01': typeof PreviewComponentsFormForm01Route
  '/preview/components/form/form-02': typeof PreviewComponentsFormForm02Route
  '/preview/components/form/form-03': typeof PreviewComponentsFormForm03Route
  '/preview/components/form/form-04': typeof PreviewComponentsFormForm04Route
  '/preview/components/form/form-05': typeof PreviewComponentsFormForm05Route
  '/preview/components/form/form-06': typeof PreviewComponentsFormForm06Route
  '/preview/components/form/form-07': typeof PreviewComponentsFormForm07Route
  '/preview/components/form/form-08': typeof PreviewComponentsFormForm08Route
  '/preview/components/form/form-09': typeof PreviewComponentsFormForm09Route
  '/preview/components/form/form-10': typeof PreviewComponentsFormForm10Route
  '/preview/components/form/form-11': typeof PreviewComponentsFormForm11Route
  '/preview/pages/landing-pages/landing-page-01': typeof PreviewPagesLandingPagesLandingPage01Route
}
export interface FileRoutesByTo {
  '/preview': typeof PreviewRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/': typeof RootLayoutIndexRoute
  '/blocks/hero-section': typeof RootLayoutBlocksHeroSectionRoute
  '/components/button': typeof RootLayoutComponentsButtonRoute
  '/components/form': typeof RootLayoutComponentsFormRoute
  '/pages/landing-pages': typeof RootLayoutPagesLandingPagesRoute
  '/blocks': typeof RootLayoutBlocksIndexRoute
  '/components': typeof RootLayoutComponentsIndexRoute
  '/pages': typeof RootLayoutPagesIndexRoute
  '/preview/blocks/hero-section/hero-section-01': typeof PreviewBlocksHeroSectionHeroSection01Route
  '/preview/components/button/button-01': typeof PreviewComponentsButtonButton01Route
  '/preview/components/button/button-02': typeof PreviewComponentsButtonButton02Route
  '/preview/components/button/button-03': typeof PreviewComponentsButtonButton03Route
  '/preview/components/form/form-01': typeof PreviewComponentsFormForm01Route
  '/preview/components/form/form-02': typeof PreviewComponentsFormForm02Route
  '/preview/components/form/form-03': typeof PreviewComponentsFormForm03Route
  '/preview/components/form/form-04': typeof PreviewComponentsFormForm04Route
  '/preview/components/form/form-05': typeof PreviewComponentsFormForm05Route
  '/preview/components/form/form-06': typeof PreviewComponentsFormForm06Route
  '/preview/components/form/form-07': typeof PreviewComponentsFormForm07Route
  '/preview/components/form/form-08': typeof PreviewComponentsFormForm08Route
  '/preview/components/form/form-09': typeof PreviewComponentsFormForm09Route
  '/preview/components/form/form-10': typeof PreviewComponentsFormForm10Route
  '/preview/components/form/form-11': typeof PreviewComponentsFormForm11Route
  '/preview/pages/landing-pages/landing-page-01': typeof PreviewPagesLandingPagesLandingPage01Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_rootLayout': typeof RootLayoutRouteRouteWithChildren
  '/preview': typeof PreviewRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/_rootLayout/': typeof RootLayoutIndexRoute
  '/_rootLayout/blocks/hero-section': typeof RootLayoutBlocksHeroSectionRoute
  '/_rootLayout/components/button': typeof RootLayoutComponentsButtonRoute
  '/_rootLayout/components/form': typeof RootLayoutComponentsFormRoute
  '/_rootLayout/pages/landing-pages': typeof RootLayoutPagesLandingPagesRoute
  '/_rootLayout/blocks/': typeof RootLayoutBlocksIndexRoute
  '/_rootLayout/components/': typeof RootLayoutComponentsIndexRoute
  '/_rootLayout/pages/': typeof RootLayoutPagesIndexRoute
  '/preview/blocks/hero-section/hero-section-01': typeof PreviewBlocksHeroSectionHeroSection01Route
  '/preview/components/button/button-01': typeof PreviewComponentsButtonButton01Route
  '/preview/components/button/button-02': typeof PreviewComponentsButtonButton02Route
  '/preview/components/button/button-03': typeof PreviewComponentsButtonButton03Route
  '/preview/components/form/form-01': typeof PreviewComponentsFormForm01Route
  '/preview/components/form/form-02': typeof PreviewComponentsFormForm02Route
  '/preview/components/form/form-03': typeof PreviewComponentsFormForm03Route
  '/preview/components/form/form-04': typeof PreviewComponentsFormForm04Route
  '/preview/components/form/form-05': typeof PreviewComponentsFormForm05Route
  '/preview/components/form/form-06': typeof PreviewComponentsFormForm06Route
  '/preview/components/form/form-07': typeof PreviewComponentsFormForm07Route
  '/preview/components/form/form-08': typeof PreviewComponentsFormForm08Route
  '/preview/components/form/form-09': typeof PreviewComponentsFormForm09Route
  '/preview/components/form/form-10': typeof PreviewComponentsFormForm10Route
  '/preview/components/form/form-11': typeof PreviewComponentsFormForm11Route
  '/preview/pages/landing-pages/landing-page-01': typeof PreviewPagesLandingPagesLandingPage01Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview'
    | '/api/search'
    | '/blocks/hero-section'
    | '/components/button'
    | '/components/form'
    | '/pages/landing-pages'
    | '/blocks/'
    | '/components/'
    | '/pages/'
    | '/preview/blocks/hero-section/hero-section-01'
    | '/preview/components/button/button-01'
    | '/preview/components/button/button-02'
    | '/preview/components/button/button-03'
    | '/preview/components/form/form-01'
    | '/preview/components/form/form-02'
    | '/preview/components/form/form-03'
    | '/preview/components/form/form-04'
    | '/preview/components/form/form-05'
    | '/preview/components/form/form-06'
    | '/preview/components/form/form-07'
    | '/preview/components/form/form-08'
    | '/preview/components/form/form-09'
    | '/preview/components/form/form-10'
    | '/preview/components/form/form-11'
    | '/preview/pages/landing-pages/landing-page-01'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/preview'
    | '/api/search'
    | '/'
    | '/blocks/hero-section'
    | '/components/button'
    | '/components/form'
    | '/pages/landing-pages'
    | '/blocks'
    | '/components'
    | '/pages'
    | '/preview/blocks/hero-section/hero-section-01'
    | '/preview/components/button/button-01'
    | '/preview/components/button/button-02'
    | '/preview/components/button/button-03'
    | '/preview/components/form/form-01'
    | '/preview/components/form/form-02'
    | '/preview/components/form/form-03'
    | '/preview/components/form/form-04'
    | '/preview/components/form/form-05'
    | '/preview/components/form/form-06'
    | '/preview/components/form/form-07'
    | '/preview/components/form/form-08'
    | '/preview/components/form/form-09'
    | '/preview/components/form/form-10'
    | '/preview/components/form/form-11'
    | '/preview/pages/landing-pages/landing-page-01'
  id:
    | '__root__'
    | '/_rootLayout'
    | '/preview'
    | '/api/search'
    | '/_rootLayout/'
    | '/_rootLayout/blocks/hero-section'
    | '/_rootLayout/components/button'
    | '/_rootLayout/components/form'
    | '/_rootLayout/pages/landing-pages'
    | '/_rootLayout/blocks/'
    | '/_rootLayout/components/'
    | '/_rootLayout/pages/'
    | '/preview/blocks/hero-section/hero-section-01'
    | '/preview/components/button/button-01'
    | '/preview/components/button/button-02'
    | '/preview/components/button/button-03'
    | '/preview/components/form/form-01'
    | '/preview/components/form/form-02'
    | '/preview/components/form/form-03'
    | '/preview/components/form/form-04'
    | '/preview/components/form/form-05'
    | '/preview/components/form/form-06'
    | '/preview/components/form/form-07'
    | '/preview/components/form/form-08'
    | '/preview/components/form/form-09'
    | '/preview/components/form/form-10'
    | '/preview/components/form/form-11'
    | '/preview/pages/landing-pages/landing-page-01'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RootLayoutRouteRoute: typeof RootLayoutRouteRouteWithChildren
  PreviewRouteRoute: typeof PreviewRouteRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_rootLayout': {
      id: '/_rootLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout/': {
      id: '/_rootLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutIndexRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout/blocks/': {
      id: '/_rootLayout/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof RootLayoutBlocksIndexRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/_rootLayout/blocks/hero-section': {
      id: '/_rootLayout/blocks/hero-section'
      path: '/blocks/hero-section'
      fullPath: '/blocks/hero-section'
      preLoaderRoute: typeof RootLayoutBlocksHeroSectionRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/_rootLayout/components/': {
      id: '/_rootLayout/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof RootLayoutComponentsIndexRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/_rootLayout/components/button': {
      id: '/_rootLayout/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof RootLayoutComponentsButtonRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/_rootLayout/components/form': {
      id: '/_rootLayout/components/form'
      path: '/components/form'
      fullPath: '/components/form'
      preLoaderRoute: typeof RootLayoutComponentsFormRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/_rootLayout/pages/': {
      id: '/_rootLayout/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof RootLayoutPagesIndexRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/_rootLayout/pages/landing-pages': {
      id: '/_rootLayout/pages/landing-pages'
      path: '/pages/landing-pages'
      fullPath: '/pages/landing-pages'
      preLoaderRoute: typeof RootLayoutPagesLandingPagesRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/preview/blocks/hero-section/hero-section-01': {
      id: '/preview/blocks/hero-section/hero-section-01'
      path: '/blocks/hero-section/hero-section-01'
      fullPath: '/preview/blocks/hero-section/hero-section-01'
      preLoaderRoute: typeof PreviewBlocksHeroSectionHeroSection01RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/button/button-01': {
      id: '/preview/components/button/button-01'
      path: '/components/button/button-01'
      fullPath: '/preview/components/button/button-01'
      preLoaderRoute: typeof PreviewComponentsButtonButton01RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/button/button-02': {
      id: '/preview/components/button/button-02'
      path: '/components/button/button-02'
      fullPath: '/preview/components/button/button-02'
      preLoaderRoute: typeof PreviewComponentsButtonButton02RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/button/button-03': {
      id: '/preview/components/button/button-03'
      path: '/components/button/button-03'
      fullPath: '/preview/components/button/button-03'
      preLoaderRoute: typeof PreviewComponentsButtonButton03RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-01': {
      id: '/preview/components/form/form-01'
      path: '/components/form/form-01'
      fullPath: '/preview/components/form/form-01'
      preLoaderRoute: typeof PreviewComponentsFormForm01RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-02': {
      id: '/preview/components/form/form-02'
      path: '/components/form/form-02'
      fullPath: '/preview/components/form/form-02'
      preLoaderRoute: typeof PreviewComponentsFormForm02RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-03': {
      id: '/preview/components/form/form-03'
      path: '/components/form/form-03'
      fullPath: '/preview/components/form/form-03'
      preLoaderRoute: typeof PreviewComponentsFormForm03RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-04': {
      id: '/preview/components/form/form-04'
      path: '/components/form/form-04'
      fullPath: '/preview/components/form/form-04'
      preLoaderRoute: typeof PreviewComponentsFormForm04RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-05': {
      id: '/preview/components/form/form-05'
      path: '/components/form/form-05'
      fullPath: '/preview/components/form/form-05'
      preLoaderRoute: typeof PreviewComponentsFormForm05RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-06': {
      id: '/preview/components/form/form-06'
      path: '/components/form/form-06'
      fullPath: '/preview/components/form/form-06'
      preLoaderRoute: typeof PreviewComponentsFormForm06RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-07': {
      id: '/preview/components/form/form-07'
      path: '/components/form/form-07'
      fullPath: '/preview/components/form/form-07'
      preLoaderRoute: typeof PreviewComponentsFormForm07RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-08': {
      id: '/preview/components/form/form-08'
      path: '/components/form/form-08'
      fullPath: '/preview/components/form/form-08'
      preLoaderRoute: typeof PreviewComponentsFormForm08RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-09': {
      id: '/preview/components/form/form-09'
      path: '/components/form/form-09'
      fullPath: '/preview/components/form/form-09'
      preLoaderRoute: typeof PreviewComponentsFormForm09RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-10': {
      id: '/preview/components/form/form-10'
      path: '/components/form/form-10'
      fullPath: '/preview/components/form/form-10'
      preLoaderRoute: typeof PreviewComponentsFormForm10RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/components/form/form-11': {
      id: '/preview/components/form/form-11'
      path: '/components/form/form-11'
      fullPath: '/preview/components/form/form-11'
      preLoaderRoute: typeof PreviewComponentsFormForm11RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
    '/preview/pages/landing-pages/landing-page-01': {
      id: '/preview/pages/landing-pages/landing-page-01'
      path: '/pages/landing-pages/landing-page-01'
      fullPath: '/preview/pages/landing-pages/landing-page-01'
      preLoaderRoute: typeof PreviewPagesLandingPagesLandingPage01RouteImport
      parentRoute: typeof PreviewRouteRoute
    }
  }
}

interface RootLayoutRouteRouteChildren {
  RootLayoutIndexRoute: typeof RootLayoutIndexRoute
  RootLayoutBlocksHeroSectionRoute: typeof RootLayoutBlocksHeroSectionRoute
  RootLayoutComponentsButtonRoute: typeof RootLayoutComponentsButtonRoute
  RootLayoutComponentsFormRoute: typeof RootLayoutComponentsFormRoute
  RootLayoutPagesLandingPagesRoute: typeof RootLayoutPagesLandingPagesRoute
  RootLayoutBlocksIndexRoute: typeof RootLayoutBlocksIndexRoute
  RootLayoutComponentsIndexRoute: typeof RootLayoutComponentsIndexRoute
  RootLayoutPagesIndexRoute: typeof RootLayoutPagesIndexRoute
}

const RootLayoutRouteRouteChildren: RootLayoutRouteRouteChildren = {
  RootLayoutIndexRoute: RootLayoutIndexRoute,
  RootLayoutBlocksHeroSectionRoute: RootLayoutBlocksHeroSectionRoute,
  RootLayoutComponentsButtonRoute: RootLayoutComponentsButtonRoute,
  RootLayoutComponentsFormRoute: RootLayoutComponentsFormRoute,
  RootLayoutPagesLandingPagesRoute: RootLayoutPagesLandingPagesRoute,
  RootLayoutBlocksIndexRoute: RootLayoutBlocksIndexRoute,
  RootLayoutComponentsIndexRoute: RootLayoutComponentsIndexRoute,
  RootLayoutPagesIndexRoute: RootLayoutPagesIndexRoute,
}

const RootLayoutRouteRouteWithChildren = RootLayoutRouteRoute._addFileChildren(
  RootLayoutRouteRouteChildren,
)

interface PreviewRouteRouteChildren {
  PreviewBlocksHeroSectionHeroSection01Route: typeof PreviewBlocksHeroSectionHeroSection01Route
  PreviewComponentsButtonButton01Route: typeof PreviewComponentsButtonButton01Route
  PreviewComponentsButtonButton02Route: typeof PreviewComponentsButtonButton02Route
  PreviewComponentsButtonButton03Route: typeof PreviewComponentsButtonButton03Route
  PreviewComponentsFormForm01Route: typeof PreviewComponentsFormForm01Route
  PreviewComponentsFormForm02Route: typeof PreviewComponentsFormForm02Route
  PreviewComponentsFormForm03Route: typeof PreviewComponentsFormForm03Route
  PreviewComponentsFormForm04Route: typeof PreviewComponentsFormForm04Route
  PreviewComponentsFormForm05Route: typeof PreviewComponentsFormForm05Route
  PreviewComponentsFormForm06Route: typeof PreviewComponentsFormForm06Route
  PreviewComponentsFormForm07Route: typeof PreviewComponentsFormForm07Route
  PreviewComponentsFormForm08Route: typeof PreviewComponentsFormForm08Route
  PreviewComponentsFormForm09Route: typeof PreviewComponentsFormForm09Route
  PreviewComponentsFormForm10Route: typeof PreviewComponentsFormForm10Route
  PreviewComponentsFormForm11Route: typeof PreviewComponentsFormForm11Route
  PreviewPagesLandingPagesLandingPage01Route: typeof PreviewPagesLandingPagesLandingPage01Route
}

const PreviewRouteRouteChildren: PreviewRouteRouteChildren = {
  PreviewBlocksHeroSectionHeroSection01Route:
    PreviewBlocksHeroSectionHeroSection01Route,
  PreviewComponentsButtonButton01Route: PreviewComponentsButtonButton01Route,
  PreviewComponentsButtonButton02Route: PreviewComponentsButtonButton02Route,
  PreviewComponentsButtonButton03Route: PreviewComponentsButtonButton03Route,
  PreviewComponentsFormForm01Route: PreviewComponentsFormForm01Route,
  PreviewComponentsFormForm02Route: PreviewComponentsFormForm02Route,
  PreviewComponentsFormForm03Route: PreviewComponentsFormForm03Route,
  PreviewComponentsFormForm04Route: PreviewComponentsFormForm04Route,
  PreviewComponentsFormForm05Route: PreviewComponentsFormForm05Route,
  PreviewComponentsFormForm06Route: PreviewComponentsFormForm06Route,
  PreviewComponentsFormForm07Route: PreviewComponentsFormForm07Route,
  PreviewComponentsFormForm08Route: PreviewComponentsFormForm08Route,
  PreviewComponentsFormForm09Route: PreviewComponentsFormForm09Route,
  PreviewComponentsFormForm10Route: PreviewComponentsFormForm10Route,
  PreviewComponentsFormForm11Route: PreviewComponentsFormForm11Route,
  PreviewPagesLandingPagesLandingPage01Route:
    PreviewPagesLandingPagesLandingPage01Route,
}

const PreviewRouteRouteWithChildren = PreviewRouteRoute._addFileChildren(
  PreviewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RootLayoutRouteRoute: RootLayoutRouteRouteWithChildren,
  PreviewRouteRoute: PreviewRouteRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
