/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsButtonRouteImport } from './routes/components.button'
import { Route as ComponentsTabsRouteImport } from './routes/components.tabs'
import { Route as ComponentsToggleButtonRouteImport } from './routes/components.toggle-button'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTabsRoute = ComponentsTabsRouteImport.update({
  id: '/components/tabs',
  path: '/components/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsToggleButtonRoute = ComponentsToggleButtonRouteImport.update({
  id: '/components/toggle-button',
  path: '/components/toggle-button',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/toggle-button': typeof ComponentsToggleButtonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/toggle-button': typeof ComponentsToggleButtonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/toggle-button': typeof ComponentsToggleButtonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/button'
    | '/components/tabs'
    | '/components/toggle-button'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/button'
    | '/components/tabs'
    | '/components/toggle-button'
  id:
    | '__root__'
    | '/'
    | '/components/button'
    | '/components/tabs'
    | '/components/toggle-button'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsTabsRoute: typeof ComponentsTabsRoute
  ComponentsToggleButtonRoute: typeof ComponentsToggleButtonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/components/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toggle-button': {
      id: '/components/toggle-button'
      path: '/components/toggle-button'
      fullPath: '/components/toggle-button'
      preLoaderRoute: typeof ComponentsToggleButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsTabsRoute: ComponentsTabsRoute,
  ComponentsToggleButtonRoute: ComponentsToggleButtonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
