// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartMap02Preview from "@/registry/vibe-ui/chart-map-02/chart-map-02.tsx";

export const Route = createFileRoute("/preview/charts/map/chart-map-02")({
  head: () => ({
    meta: [{ title: "Brazil election 2026 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Brazil election 2026 Preview" },
  component: () => <PreviewPage Preview={ChartMap02Preview} section="charts" />,
});
