// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import ChartMap01Preview from "@/registry/vibe-ui/chart-map-01/chart-map-01.tsx";

export const Route = createFileRoute("/preview/charts/map/chart-map-01")({
  head: () => ({
    meta: [{ title: "Population map Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Population map Preview" },
  component: () => <PreviewPage Preview={ChartMap01Preview} section="charts" />,
});
