// @generated by scripts/build-registry-routes.ts
import { createFileRoute } from "@tanstack/react-router";

import {
  RegistryCollectionPage,
  type RegistryCollectionItem,
} from "@/features/registry/components/registry-collection-page";

import HeroSection01Preview1 from "../../../../registry/vibe-ui/hero-section-01/hero-section-01.tsx";

const items = [
  {
    Preview: HeroSection01Preview1,
    description: "A centered product hero with a focused call to action.",
    name: "hero-section-01",
    title: "Hero Section 01",
  },
] satisfies RegistryCollectionItem[];

export const Route = createFileRoute("/_rootLayout/blocks/hero-section")({
  staticData: { ariaLabel: "Hero Section" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse hero section Registry items."}
      eyebrow={"Blocks"}
      items={items}
      title={"Hero Section"}
    />
  ),
});
