// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import {
  RegistryCollectionPage,
  type RegistryCollectionItem,
} from "@/features/registry/components/registry-collection-page";

const items = [
  {
    description: "A centered product hero with a focused call to action.",
    name: "hero-section-01",
    previewHref: "/preview/blocks/hero-section/hero-section-01",
    title: "Hero Section 01",
  },
] satisfies RegistryCollectionItem[];

export const Route = createFileRoute("/_rootLayout/blocks/hero-section")({
  staticData: { ariaLabel: "Hero Section" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse hero section Registry items."}
      items={items}
      title={"Hero Section"}
    />
  ),
});
