// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryCollectionPage } from "@/features/registry/components/registry-collection-page";
import registryItemHeroSection01 from "@/features/registry/data/items/hero-section-01.json";
import type { VibeBuiltRegistryItem } from "@/features/registry/types/registry";

const items = [registryItemHeroSection01] as VibeBuiltRegistryItem[];

export const Route = createFileRoute("/_rootLayout/blocks/hero-section")({
  staticData: { ariaLabel: "Hero Section" },
  component: () => (
    <RegistryCollectionPage
      description={"Browse hero section Registry items."}
      items={items}
      title={"Hero Section"}
    />
  ),
});
