// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistrySectionPage } from "@/features/registry/components/registry-section-page";

const collections = [{ title: "Hero Section", href: "/blocks/hero-section", itemCount: 1 }];

export const Route = createFileRoute("/_rootLayout/blocks/")({
  staticData: { ariaLabel: "Blocks" },
  component: () => (
    <RegistrySectionPage
      collections={collections}
      description={"Browse complete interface sections and application patterns."}
      title={"Blocks"}
    />
  ),
});
