// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Form03Preview from "@/registry/vibe-ui/form-03/form-03.tsx";

export const Route = createFileRoute("/preview/components/form/form-03")({
  head: () => ({
    meta: [{ title: "Form 03 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 03 Preview" },
  component: () => <PreviewPage Preview={Form03Preview} type="registry:component" />,
});
