// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryPreviewPage } from "@/features/registry/components/registry-preview-page";
import Form01Preview from "@/registry/vibe-ui/form-01/form-01.tsx";

export const Route = createFileRoute("/preview/components/form/form-01")({
  head: () => ({
    meta: [{ title: "Form 01 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 01 Preview" },
  component: () => <RegistryPreviewPage Preview={Form01Preview} type="registry:component" />,
});
