// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Form09Preview from "@/registry/vibe-ui/form-09/form-09.tsx";

export const Route = createFileRoute("/preview/components/form/form-09")({
  head: () => ({
    meta: [{ title: "Form 09 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 09 Preview" },
  component: () => <PreviewPage Preview={Form09Preview} section="components" />,
});
