// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Form07Preview from "@/registry/vibe-ui/form-07/form-07.tsx";

export const Route = createFileRoute("/preview/components/form/form-07")({
  head: () => ({
    meta: [{ title: "Form 07 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 07 Preview" },
  component: () => <PreviewPage Preview={Form07Preview} section="components" />,
});
