// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryPreviewPage } from "@/features/registry/components/registry-preview-page";
import Form08Preview from "@/registry/vibe-ui/form-08/form-08.tsx";

export const Route = createFileRoute("/preview/components/form/form-08")({
  head: () => ({
    meta: [{ title: "Form 08 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 08 Preview" },
  component: () => <RegistryPreviewPage Preview={Form08Preview} type="registry:component" />,
});
