// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryPreviewPage } from "@/features/registry/components/registry-preview-page";
import Form04Preview from "@/registry/vibe-ui/form-04/form-04.tsx";

export const Route = createFileRoute("/preview/components/form/form-04")({
  head: () => ({
    meta: [{ title: "Form 04 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 04 Preview" },
  component: () => <RegistryPreviewPage Preview={Form04Preview} type="registry:component" />,
});
