// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryPreviewPage } from "@/features/registry/components/registry-preview-page";
import Form06Preview from "@/registry/vibe-ui/form-06/form-06.tsx";

export const Route = createFileRoute("/preview/components/form/form-06")({
  head: () => ({
    meta: [{ title: "Form 06 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 06 Preview" },
  component: () => <RegistryPreviewPage Preview={Form06Preview} type="registry:component" />,
});
