// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Form05Preview from "@/registry/vibe-ui/form-05/form-05.tsx";

export const Route = createFileRoute("/preview/components/form/form-05")({
  head: () => ({
    meta: [{ title: "Form 05 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 05 Preview" },
  component: () => <PreviewPage Preview={Form05Preview} section="components" />,
});
