// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryPreviewPage } from "@/features/registry/components/registry-preview-page";
import Form02Preview from "@/registry/vibe-ui/form-02/form-02.tsx";

export const Route = createFileRoute("/preview/components/form/form-02")({
  head: () => ({
    meta: [{ title: "Form 02 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 02 Preview" },
  component: () => <RegistryPreviewPage Preview={Form02Preview} type="registry:component" />,
});
