// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Form10Preview from "@/registry/vibe-ui/form-10/form-10.tsx";

export const Route = createFileRoute("/preview/components/form/form-10")({
  head: () => ({
    meta: [{ title: "Form 10 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 10 Preview" },
  component: () => <PreviewPage Preview={Form10Preview} section="components" />,
});
