// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { PreviewPage } from "@/features/registry/components/preview-page";
import Form11Preview from "@/registry/vibe-ui/form-11/form-11.tsx";

export const Route = createFileRoute("/preview/components/form/form-11")({
  head: () => ({
    meta: [{ title: "Form 11 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 11 Preview" },
  component: () => <PreviewPage Preview={Form11Preview} type="registry:component" />,
});
