// @generated by scripts/build-registry.ts
import { createFileRoute } from "@tanstack/react-router";

import { RegistryPreviewPage } from "@/features/registry/components/registry-preview-page";
import Form07Preview from "@/registry/vibe-ui/form-07/form-07.tsx";

export const Route = createFileRoute("/preview/components/form/form-07")({
  head: () => ({
    meta: [{ title: "Form 07 Preview – VibeUI" }],
  }),
  staticData: { ariaLabel: "Form 07 Preview" },
  component: () => <RegistryPreviewPage Preview={Form07Preview} type="registry:component" />,
});
